---
# tasks file for apt_repos

# Not installed in bulleyes pve templates
- name: Install gpg if not
  apt:
    name: gpg
    state: present
    update_cache: yes

- name: See distribution info
  debug:
    var: '{{ item }}'
    verbosity: 2
  loop:
  - ansible_distribution
  - apt_repos_url
  - apt_repos_security_url
  - apt_repos_components
  - apt_repos_key_url
  - apt_repositories_sources_list

- name: Remove all existing repositories with force-repos tag 
  block:
  - name: A task just to show we are removing apt configuration
    debug:
      msg: "We are removing existing apt configuration"
      verbosity: 0
  
  - name: Remove all files in /etc/apt/sources.list.d/
    file: 
      path: /etc/apt/sources.list.d/
      state: absent

  - name: re-create empty /etc/apt/sources.list.d/
    file: 
      path: /etc/apt/sources.list.d/
      state: directory
  when: apt_repos_remove_previous 
  # this didn't work
  # tags:
  # - never
  # - force-repos

- name: Build /etc/apt/source.list from template
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  register: apt_repositories_sources_list_update

- name: Add keys for the repositories (key URL)
  apt_key:
    url: "{{ apt_repositories_repo.key }}"
    state: "{{ apt_repositories_repo.state | default('present') }}"
  when: apt_repositories_repo.key is defined
  loop: "{{ apt_repositories_sources_list + apt_repositories_extra }}"
  loop_control:
    loop_var: apt_repositories_repo

- name: Add keys for the repositories (from keys server)
  apt_key: 
    keyserver: "{{ apt_repositories_repo.keyserver }}"
    id: "{{ apt_repositories_repoitem.key_id }}"
    state: "{{ apt_repositories_repo.state | default('present') }}"
  when: apt_repositories_repo.key_id is defined and apt_repositories_repo.keyserver is defined
  loop: "{{ apt_repositories_sources_list + apt_repositories_extra }}"
  loop_control:
    loop_var: apt_repositories_repo

- name: Add declared repositories
  apt_repository:
    repo: "{{ apt_repositories_repo.repo }}"
    filename: "{{ apt_repositories_repo.filename | default(omit) }}"
    state: "{{ apt_repositories_repo.state | default('present') }}"
  loop: "{{ apt_repositories_extra }}"
  loop_control:
    loop_var: apt_repositories_repo
  register: apt_repositories_repos_added

- name: Update apt cache
  apt: 
    update_cache: yes
  when: ( apt_repositories_repos_added is changed ) or ( apt_repositories_sources_list_update is changed )

...
