---
# tasks file for apt_repos

- name: Remove all existing repositories with force-repos tag 
  block:
  - name: A task just to show we are removing apt configuration
    debug:
      msg: "We are removing existing apt configuration"
      verbosity: 0
  
  - name: remove all files in /etc/apt/sources.list.d/
    file: 
      path: /etc/apt/sources.list.d/
      state: absent

  - name: re-create empty /etc/apt/sources.list.d/
    file: 
      path: /etc/apt/sources.list.d/
      state: directory
  when: apt_repos_remove_previous 
  # this didn't work
  # tags:
  # - never
  # - force-repos

- name: build /etc/apt/source.list from template
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  register: sources_list

- name: add keys for the repositories (key URL)
  apt_key:
    url: "{{ item.key }}"
    state: "{{ item.state | default('present') }}"
  when: item.key is defined
  loop: "{{ apt_repositories_sources_list + apt_repositories_extra }}"

- name: add keys for the repositories (from keys server)
  apt_key: 
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.key_id }}"
    state: "{{ item.state | default('present') }}"
  when: item.key_id is defined and item.keyserver is defined
  loop: "{{ apt_repositories_sources_list + apt_repositories_extra }}"

- name: add declared repositories
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ apt_repositories_extra }}"
  register: repos_added

- name: update apt cache
  apt: 
    update_cache: yes
  when: (repos_added is changed) or (sources_list is changed)
